export const leaveRequestStatuses = {
	2: { stateName: 'Draft', color: '#343a40', textColor: '#ffffff' },
	3: { stateName: 'In Progress', color: '#007bff', textColor: '#ffffff' },
	4: { stateName: 'Completed', color: '#f8f9fa', textColor: '#212529' },
	5: { stateName: 'New', color: '#ECE9F2', textColor: '#000000' },
	6: { stateName: 'Contacted', color: '#ffc107', textColor: '#212529' },
	7: { stateName: 'Document Recieved', color: '#343a40', textColor: '#ffffff' },
	8: { stateName: 'Invoice', color: '#28a745', textColor: '#ffffff' },
	9: { stateName: 'New Lead', color: '#17a2b8', textColor: '#ffffff' },
	10: { stateName: 'Email Delivery', color: '#ffc107', textColor: '#212529' },
	11: { stateName: 'Potential', color: '#ffd700', textColor: '#212529' },
	12: { stateName: 'Impossible', color: '#dc3545', textColor: '#ffffff' },
	13: { stateName: 'Apply in future', color: '#6f42c1', textColor: '#ffffff' },
	14: { stateName: 'Invoice', color: '#28a745', textColor: '#ffffff' },
	15: { stateName: 'Sold', color: '#6c757d', textColor: '#ffffff' },
	16: { stateName: 'Email Delivery', color: '#343a40', textColor: '#ffffff' },
	17: { stateName: 'Hold', color: '#007bff', textColor: '#ffffff' },
	18: { stateName: 'Expired', color: '#007bff', textColor: '#ffffff' },
	19: { stateName: 'Approved', color: '#C3FFA6', textColor: '#000000' },
	20: { stateName: 'Followup', color: '#343a40', textColor: '#ffffff' },
	21: { stateName: 'Callback', color: '#343a40', textColor: '#ffffff' },
	22: { stateName: 'No response', color: '#343a40', textColor: '#ffffff' },
	23: { stateName: 'Reject', color: '#ffc107', textColor: '#212529' },
	24: { stateName: 'Pending Approval', color: '#17a2b8', textColor: '#ffffff' },
	25: { stateName: 'Sample Approve1', color: '#343a40', textColor: '#ffffff' },
	26: { stateName: 'Sample Approve2', color: '#343a40', textColor: '#ffffff' },
	27: { stateName: 'Sample Reject1', color: '#007bff', textColor: '#ffffff' },
	28: { stateName: 'Sample Reject2', color: '#007bff', textColor: '#ffffff' },
	29: {
		stateName: 'Awaiting PM Approval',
		color: '#007bff',
		textColor: '#ffffff',
	},
	30: {
		stateName: 'Supervisor Rejected',
		color: '#ffc107',
		textColor: '#212529',
	},
	31: { stateName: 'Supervisor Hold', color: '#f8f9fa', textColor: '#212529' },
	32: {
		stateName: 'Awaiting HR Approval',
		color: '#007bff',
		textColor: '#ffffff',
	},
	33: { stateName: 'PM Rejected', color: '#ffc107', textColor: '#212529' },
	34: { stateName: 'PM Hold', color: '#f8f9fa', textColor: '#212529' },
	35: { stateName: 'HR Approved', color: '#28a745', textColor: '#ffffff' },
	36: { stateName: 'Rejected', color: '#ffc107', textColor: '#212529' },
	37: { stateName: 'Approval Waiting', color: '#17a2b8', textColor: '#ffffff' },
	1037: { stateName: 'Section Head', color: '#343a40', textColor: '#ffffff' },
	1038: { stateName: 'Submit', color: '#007bff', textColor: '#ffffff' },
	1039: { stateName: 'Approved RW', color: '#343a40', textColor: '#ffffff' },
	1040: { stateName: 'NewRW', color: '#007bff', textColor: '#ffffff' },
	1042: { stateName: 'Rejected RW', color: '#17a2b8', textColor: '#ffffff' },
};
